//定义模块
angular.module("myApp",[])
.controller("demo4Con",["$scope",function($scope){
	var datas=[
		{
			Firstname:"dang",
			Lastname:"nana",
			Gender:"Female",
			Salary:18088,
			Ysalary:123356,
			Birthday:"1470524904525"
		},
		{
			Firstname:"merry",
			Lastname:"lili",
			Gender:"Male",
			Salary:16000,
			Ysalary:180080,
			Birthday:"1470477704525"
		},
		{
			Firstname:"kitty",
			Lastname:"zhangsan",
			Gender:"Male",
			Salary:15505,
			Ysalary:149650,
			Birthday:"1380556916345"
		},
		{
			Firstname:"jack",
			Lastname:"lisi",
			Gender:"Female",
			Salary:17532,
			Ysalary:197532,
			Birthday:"1470477904525"
		},
		{
			Firstname:"wang",
			Lastname:"rose",
			Gender:"Female",
			Salary:18357,
			Ysalary:149650,
			Birthday:"1470535903926"
		}
	]
	$scope.one="Firstname";
	$scope.one="Salary";
	$scope.bool=0;
	$scope.datas=datas;
	$scope.searchtext1="";
	$scope.searchtext2="";
	$scope.dis=true;
	$scope.one=function(){
		chage("one","Firstname")
	}
	$scope.two=function(){
		chage("two","Lastname")
	}
	$scope.three=function(){
		chage("three","Gender")
	}
	$scope.four=function(){
		chage("four","Salary")
	}
	$scope.five=function(){
		chage("five","Ysalary")
	}
	$scope.six=function(){
		chage("six","Birthday")
	}
	function chage(value,str){
		if($scope.value==str){
			$scope.value="-"+str;
		}else{
			$scope.value=str;
		}
	}
	$scope.one1=function(){
		$scope.a=true;
		$scope.c=false;
		$scope.d=false;
		$scope.e=false;
		$scope.f=false;
		$scope.g=false;
	}
	$scope.one2=function(){
		$scope.a=false;
		$scope.c=true;
		$scope.d=false;
		$scope.e=false;
		$scope.f=false;
		$scope.g=false;
	}
	$scope.one3=function(){
		$scope.a=false;
		$scope.c=false;
		$scope.d=true;
		$scope.e=false;
		$scope.f=false;
		$scope.g=false;
	}
	$scope.one4=function(){
		$scope.a=false;
		$scope.c=false;
		$scope.d=false;
		$scope.e=true;
		$scope.f=false;
		$scope.g=false;
	}
	$scope.one5=function(){
		$scope.a=false;
		$scope.c=false;
		$scope.d=false;
		$scope.e=false;
		$scope.f=true;
		$scope.g=false;
	}
	$scope.one6=function(){
		$scope.a=false;
		$scope.c=false;
		$scope.d=false;
		$scope.e=false;
		$scope.f=false;
		$scope.g=true;
	}
}])